window.esdocSearchIndex = [
  [
    "rtc-engine/js/channel.js~channel",
    "class/js/Channel.js~Channel.html",
    "<span>Channel</span> <span class=\"search-result-import-path\">rtc-engine/js/Channel.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/chunkproducer.js~chunkproducer",
    "class/js/ChunkProducer.js~ChunkProducer.html",
    "<span>ChunkProducer</span> <span class=\"search-result-import-path\">rtc-engine/js/ChunkProducer.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/util/intervaltimer.js~intervaltimer",
    "class/js/util/IntervalTimer.js~IntervalTimer.html",
    "<span>IntervalTimer</span> <span class=\"search-result-import-path\">rtc-engine/js/util/IntervalTimer.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/util/listenermanager.js~listenermanager",
    "class/js/util/ListenerManager.js~ListenerManager.html",
    "<span>ListenerManager</span> <span class=\"search-result-import-path\">rtc-engine/js/util/ListenerManager.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/signaler/localsignaler.js~localsignaler",
    "class/js/signaler/LocalSignaler.js~LocalSignaler.html",
    "<span>LocalSignaler</span> <span class=\"search-result-import-path\">rtc-engine/js/signaler/LocalSignaler.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/util/mitt.js~mitt",
    "class/js/util/Mitt.js~Mitt.html",
    "<span>Mitt</span> <span class=\"search-result-import-path\">rtc-engine/js/util/Mitt.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/util/observableentry.js~observableentry",
    "class/js/util/ObservableEntry.js~ObservableEntry.html",
    "<span>ObservableEntry</span> <span class=\"search-result-import-path\">rtc-engine/js/util/ObservableEntry.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/util/observablemap.js~observablemap",
    "class/js/util/ObservableMap.js~ObservableMap.html",
    "<span>ObservableMap</span> <span class=\"search-result-import-path\">rtc-engine/js/util/ObservableMap.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/util/observablequeue.js~observablequeue",
    "class/js/util/ObservableQueue.js~ObservableQueue.html",
    "<span>ObservableQueue</span> <span class=\"search-result-import-path\">rtc-engine/js/util/ObservableQueue.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/util/queue.js~queue",
    "class/js/util/Queue.js~Queue.html",
    "<span>Queue</span> <span class=\"search-result-import-path\">rtc-engine/js/util/Queue.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/rtcsocket.js~rtcsocket",
    "class/js/RTCSocket.js~RTCSocket.html",
    "<span>RTCSocket</span> <span class=\"search-result-import-path\">rtc-engine/js/RTCSocket.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/readabletransaction.js~readabletransaction",
    "class/js/ReadableTransaction.js~ReadableTransaction.html",
    "<span>ReadableTransaction</span> <span class=\"search-result-import-path\">rtc-engine/js/ReadableTransaction.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/signaler/base.js~signalerbase",
    "class/js/signaler/Base.js~SignalerBase.html",
    "<span>SignalerBase</span> <span class=\"search-result-import-path\">rtc-engine/js/signaler/Base.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/util/timeouttimer.js~timeouttimer",
    "class/js/util/TimeoutTimer.js~TimeoutTimer.html",
    "<span>TimeoutTimer</span> <span class=\"search-result-import-path\">rtc-engine/js/util/TimeoutTimer.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/transaction.js~transaction",
    "class/js/Transaction.js~Transaction.html",
    "<span>Transaction</span> <span class=\"search-result-import-path\">rtc-engine/js/Transaction.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/util/observableentry.js~waitentry",
    "class/js/util/ObservableEntry.js~WaitEntry.html",
    "<span>WaitEntry</span> <span class=\"search-result-import-path\">rtc-engine/js/util/ObservableEntry.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/writabletransaction.js~writabletransaction",
    "class/js/WritableTransaction.js~WritableTransaction.html",
    "<span>WritableTransaction</span> <span class=\"search-result-import-path\">rtc-engine/js/WritableTransaction.js</span>",
    "class"
  ],
  [
    "rtc-engine/js/util/createlogger.js~createlogger",
    "function/index.html#static-function-createLogger",
    "<span>createLogger</span> <span class=\"search-result-import-path\">rtc-engine/js/util/createLogger.js</span>",
    "function"
  ],
  [
    "rtc-engine/js/util/createlogger.js~disablelog",
    "function/index.html#static-function-disableLog",
    "<span>disableLog</span> <span class=\"search-result-import-path\">rtc-engine/js/util/createLogger.js</span>",
    "function"
  ],
  [
    "rtc-engine/js/util/eta.js~makeeta",
    "function/index.html#static-function-makeEta",
    "<span>makeEta</span> <span class=\"search-result-import-path\">rtc-engine/js/util/eta.js</span>",
    "function"
  ],
  [
    "rtc-engine/js/util/observableentry.js~observe",
    "function/index.html#static-function-observe",
    "<span>observe</span> <span class=\"search-result-import-path\">rtc-engine/js/util/ObservableEntry.js</span>",
    "function"
  ],
  [
    "rtc-engine/js/util/once.js~once",
    "function/index.html#static-function-once",
    "<span>once</span> <span class=\"search-result-import-path\">rtc-engine/js/util/once.js</span>",
    "function"
  ],
  [
    "rtc-engine/js/util/prettybytes.js~prettybytes",
    "function/index.html#static-function-prettyBytes",
    "<span>prettyBytes</span> <span class=\"search-result-import-path\">rtc-engine/js/util/prettyBytes.js</span>",
    "function"
  ],
  [
    "rtc-engine/js/util/observableentry.js~wait",
    "function/index.html#static-function-wait",
    "<span>wait</span> <span class=\"search-result-import-path\">rtc-engine/js/util/ObservableEntry.js</span>",
    "function"
  ],
  [
    "rtc-engine/js/util/observableentry.js~waitall",
    "function/index.html#static-function-waitAll",
    "<span>waitAll</span> <span class=\"search-result-import-path\">rtc-engine/js/util/ObservableEntry.js</span>",
    "function"
  ],
  [
    "js/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "js/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "js/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "js/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "js/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "js/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "js/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "js/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "js/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "js/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "js/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "js/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "js/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "js/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "js/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "js/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "js/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "js/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "js/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "js/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "js/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "js/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "js/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "js/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "js/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "js/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "js/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "js/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "js/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "js/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "js/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "js/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "js/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "js/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "js/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "js/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "js/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "js/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "js/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "js/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "js/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "js/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "js/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "js/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "js/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "js/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "js/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "js/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "js/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "js/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "js/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "js/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "js/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "js/.external-ecmascript.js~String",
    "external"
  ],
  [
    "js/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "js/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "js/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "js/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "js/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "js/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "js/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "js/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "js/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "js/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "js/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "js/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "js/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "js/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "js/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "js/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "js/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "js/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "js/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "js/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "js/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "js/.external-ecmascript.js~function",
    "external"
  ],
  [
    "js/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "js/.external-ecmascript.js~null",
    "external"
  ],
  [
    "js/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "js/.external-ecmascript.js~number",
    "external"
  ],
  [
    "js/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "js/.external-ecmascript.js~object",
    "external"
  ],
  [
    "js/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "js/.external-ecmascript.js~string",
    "external"
  ],
  [
    "js/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "js/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "js/channel.js",
    "file/js/Channel.js.html",
    "js/Channel.js",
    "file"
  ],
  [
    "js/channel.js~channel#constructor",
    "class/js/Channel.js~Channel.html#instance-constructor-constructor",
    "js/Channel.js~Channel#constructor",
    "method"
  ],
  [
    "js/channel.js~channel#engine",
    "class/js/Channel.js~Channel.html#instance-member-engine",
    "js/Channel.js~Channel#engine",
    "member"
  ],
  [
    "js/channel.js~channel#filessent",
    "class/js/Channel.js~Channel.html#instance-member-filesSent",
    "js/Channel.js~Channel#filesSent",
    "member"
  ],
  [
    "js/channel.js~channel#label",
    "class/js/Channel.js~Channel.html#instance-member-label",
    "js/Channel.js~Channel#label",
    "member"
  ],
  [
    "js/channel.js~channel#receivetransaction",
    "class/js/Channel.js~Channel.html#instance-method-receiveTransaction",
    "js/Channel.js~Channel#receiveTransaction",
    "method"
  ],
  [
    "js/channel.js~channel#send",
    "class/js/Channel.js~Channel.html#instance-method-send",
    "js/Channel.js~Channel#send",
    "method"
  ],
  [
    "js/channel.js~channel#socket",
    "class/js/Channel.js~Channel.html#instance-member-socket",
    "js/Channel.js~Channel#socket",
    "member"
  ],
  [
    "js/chunkproducer.js",
    "file/js/ChunkProducer.js.html",
    "js/ChunkProducer.js",
    "file"
  ],
  [
    "js/chunkproducer.js~chunkproducer#buffer",
    "class/js/ChunkProducer.js~ChunkProducer.html#instance-member-buffer",
    "js/ChunkProducer.js~ChunkProducer#buffer",
    "member"
  ],
  [
    "js/chunkproducer.js~chunkproducer#constructor",
    "class/js/ChunkProducer.js~ChunkProducer.html#instance-constructor-constructor",
    "js/ChunkProducer.js~ChunkProducer#constructor",
    "method"
  ],
  [
    "js/chunkproducer.js~chunkproducer#flush",
    "class/js/ChunkProducer.js~ChunkProducer.html#instance-method-flush",
    "js/ChunkProducer.js~ChunkProducer#flush",
    "method"
  ],
  [
    "js/chunkproducer.js~chunkproducer#size",
    "class/js/ChunkProducer.js~ChunkProducer.html#instance-member-size",
    "js/ChunkProducer.js~ChunkProducer#size",
    "member"
  ],
  [
    "js/chunkproducer.js~chunkproducer#transform",
    "class/js/ChunkProducer.js~ChunkProducer.html#instance-method-transform",
    "js/ChunkProducer.js~ChunkProducer#transform",
    "method"
  ],
  [
    "js/rtcsocket.js",
    "file/js/RTCSocket.js.html",
    "js/RTCSocket.js",
    "file"
  ],
  [
    "js/rtcsocket.js~rtcsocket#close",
    "class/js/RTCSocket.js~RTCSocket.html#instance-method-close",
    "js/RTCSocket.js~RTCSocket#close",
    "method"
  ],
  [
    "js/rtcsocket.js~rtcsocket#closed",
    "class/js/RTCSocket.js~RTCSocket.html#instance-member-closed",
    "js/RTCSocket.js~RTCSocket#closed",
    "member"
  ],
  [
    "js/rtcsocket.js~rtcsocket#constructor",
    "class/js/RTCSocket.js~RTCSocket.html#instance-constructor-constructor",
    "js/RTCSocket.js~RTCSocket#constructor",
    "method"
  ],
  [
    "js/rtcsocket.js~rtcsocket#datachannel",
    "class/js/RTCSocket.js~RTCSocket.html#instance-member-dataChannel",
    "js/RTCSocket.js~RTCSocket#dataChannel",
    "member"
  ],
  [
    "js/rtcsocket.js~rtcsocket#label",
    "class/js/RTCSocket.js~RTCSocket.html#instance-member-label",
    "js/RTCSocket.js~RTCSocket#label",
    "member"
  ],
  [
    "js/rtcsocket.js~rtcsocket#logger",
    "class/js/RTCSocket.js~RTCSocket.html#instance-member-logger",
    "js/RTCSocket.js~RTCSocket#logger",
    "member"
  ],
  [
    "js/rtcsocket.js~rtcsocket#ready",
    "class/js/RTCSocket.js~RTCSocket.html#instance-member-ready",
    "js/RTCSocket.js~RTCSocket#ready",
    "member"
  ],
  [
    "js/rtcsocket.js~rtcsocket#recvdata",
    "class/js/RTCSocket.js~RTCSocket.html#instance-method-recvData",
    "js/RTCSocket.js~RTCSocket#recvData",
    "method"
  ],
  [
    "js/rtcsocket.js~rtcsocket#write",
    "class/js/RTCSocket.js~RTCSocket.html#instance-method-write",
    "js/RTCSocket.js~RTCSocket#write",
    "method"
  ],
  [
    "js/rtcsocket.js~rtcsocket#writeevent",
    "class/js/RTCSocket.js~RTCSocket.html#instance-method-writeEvent",
    "js/RTCSocket.js~RTCSocket#writeEvent",
    "method"
  ],
  [
    "js/readabletransaction.js",
    "file/js/ReadableTransaction.js.html",
    "js/ReadableTransaction.js",
    "file"
  ],
  [
    "js/readabletransaction.js~readabletransaction#aborted",
    "class/js/ReadableTransaction.js~ReadableTransaction.html#instance-member-aborted",
    "js/ReadableTransaction.js~ReadableTransaction#aborted",
    "member"
  ],
  [
    "js/readabletransaction.js~readabletransaction#bufferfullinformed",
    "class/js/ReadableTransaction.js~ReadableTransaction.html#instance-member-bufferFullInformed",
    "js/ReadableTransaction.js~ReadableTransaction#bufferFullInformed",
    "member"
  ],
  [
    "js/readabletransaction.js~readabletransaction#cancel",
    "class/js/ReadableTransaction.js~ReadableTransaction.html#instance-method-cancel",
    "js/ReadableTransaction.js~ReadableTransaction#cancel",
    "method"
  ],
  [
    "js/readabletransaction.js~readabletransaction#cancelreason",
    "class/js/ReadableTransaction.js~ReadableTransaction.html#instance-member-cancelReason",
    "js/ReadableTransaction.js~ReadableTransaction#cancelReason",
    "member"
  ],
  [
    "js/readabletransaction.js~readabletransaction#canceled",
    "class/js/ReadableTransaction.js~ReadableTransaction.html#instance-member-canceled",
    "js/ReadableTransaction.js~ReadableTransaction#canceled",
    "member"
  ],
  [
    "js/readabletransaction.js~readabletransaction#constructor",
    "class/js/ReadableTransaction.js~ReadableTransaction.html#instance-constructor-constructor",
    "js/ReadableTransaction.js~ReadableTransaction#constructor",
    "method"
  ],
  [
    "js/readabletransaction.js~readabletransaction#pause",
    "class/js/ReadableTransaction.js~ReadableTransaction.html#instance-method-pause",
    "js/ReadableTransaction.js~ReadableTransaction#pause",
    "method"
  ],
  [
    "js/readabletransaction.js~readabletransaction#resume",
    "class/js/ReadableTransaction.js~ReadableTransaction.html#instance-method-resume",
    "js/ReadableTransaction.js~ReadableTransaction#resume",
    "method"
  ],
  [
    "js/readabletransaction.js~readabletransaction#stop",
    "class/js/ReadableTransaction.js~ReadableTransaction.html#instance-method-stop",
    "js/ReadableTransaction.js~ReadableTransaction#stop",
    "method"
  ],
  [
    "js/readabletransaction.js~readabletransaction#stream",
    "class/js/ReadableTransaction.js~ReadableTransaction.html#instance-member-stream",
    "js/ReadableTransaction.js~ReadableTransaction#stream",
    "member"
  ],
  [
    "js/transaction.js",
    "file/js/Transaction.js.html",
    "js/Transaction.js",
    "file"
  ],
  [
    "js/transaction.js~transaction#constructor",
    "class/js/Transaction.js~Transaction.html#instance-constructor-constructor",
    "js/Transaction.js~Transaction#constructor",
    "method"
  ],
  [
    "js/transaction.js~transaction#done",
    "class/js/Transaction.js~Transaction.html#instance-member-done",
    "js/Transaction.js~Transaction#done",
    "member"
  ],
  [
    "js/transaction.js~transaction#eta",
    "class/js/Transaction.js~Transaction.html#instance-get-eta",
    "js/Transaction.js~Transaction#eta",
    "member"
  ],
  [
    "js/transaction.js~transaction#initprogresstracking",
    "class/js/Transaction.js~Transaction.html#instance-method-initProgressTracking",
    "js/Transaction.js~Transaction#initProgressTracking",
    "method"
  ],
  [
    "js/transaction.js~transaction#label",
    "class/js/Transaction.js~Transaction.html#instance-member-label",
    "js/Transaction.js~Transaction#label",
    "member"
  ],
  [
    "js/transaction.js~transaction#lastpausedtimestamp",
    "class/js/Transaction.js~Transaction.html#instance-member-lastPausedTimestamp",
    "js/Transaction.js~Transaction#lastPausedTimestamp",
    "member"
  ],
  [
    "js/transaction.js~transaction#logger",
    "class/js/Transaction.js~Transaction.html#instance-member-logger",
    "js/Transaction.js~Transaction#logger",
    "member"
  ],
  [
    "js/transaction.js~transaction#metadata",
    "class/js/Transaction.js~Transaction.html#instance-member-metadata",
    "js/Transaction.js~Transaction#metadata",
    "member"
  ],
  [
    "js/transaction.js~transaction#pause",
    "class/js/Transaction.js~Transaction.html#instance-method-pause",
    "js/Transaction.js~Transaction#pause",
    "method"
  ],
  [
    "js/transaction.js~transaction#paused",
    "class/js/Transaction.js~Transaction.html#instance-member-paused",
    "js/Transaction.js~Transaction#paused",
    "member"
  ],
  [
    "js/transaction.js~transaction#pausedmilliseconds",
    "class/js/Transaction.js~Transaction.html#instance-member-pausedMilliSeconds",
    "js/Transaction.js~Transaction#pausedMilliSeconds",
    "member"
  ],
  [
    "js/transaction.js~transaction#processed",
    "class/js/Transaction.js~Transaction.html#instance-member-processed",
    "js/Transaction.js~Transaction#processed",
    "member"
  ],
  [
    "js/transaction.js~transaction#progress",
    "class/js/Transaction.js~Transaction.html#instance-get-progress",
    "js/Transaction.js~Transaction#progress",
    "member"
  ],
  [
    "js/transaction.js~transaction#progresstracker",
    "class/js/Transaction.js~Transaction.html#instance-member-progressTracker",
    "js/Transaction.js~Transaction#progressTracker",
    "member"
  ],
  [
    "js/transaction.js~transaction#resume",
    "class/js/Transaction.js~Transaction.html#instance-method-resume",
    "js/Transaction.js~Transaction#resume",
    "method"
  ],
  [
    "js/transaction.js~transaction#socket",
    "class/js/Transaction.js~Transaction.html#instance-member-socket",
    "js/Transaction.js~Transaction#socket",
    "member"
  ],
  [
    "js/transaction.js~transaction#speed",
    "class/js/Transaction.js~Transaction.html#instance-get-speed",
    "js/Transaction.js~Transaction#speed",
    "member"
  ],
  [
    "js/transaction.js~transaction#stopreport",
    "class/js/Transaction.js~Transaction.html#instance-method-stopReport",
    "js/Transaction.js~Transaction#stopReport",
    "method"
  ],
  [
    "js/transaction.js~transaction#timeout",
    "class/js/Transaction.js~Transaction.html#instance-member-timeout",
    "js/Transaction.js~Transaction#timeout",
    "member"
  ],
  [
    "js/writabletransaction.js",
    "file/js/WritableTransaction.js.html",
    "js/WritableTransaction.js",
    "file"
  ],
  [
    "js/writabletransaction.js~writabletransaction#abortcontroller",
    "class/js/WritableTransaction.js~WritableTransaction.html#instance-member-abortController",
    "js/WritableTransaction.js~WritableTransaction#abortController",
    "member"
  ],
  [
    "js/writabletransaction.js~writabletransaction#aborted",
    "class/js/WritableTransaction.js~WritableTransaction.html#instance-member-aborted",
    "js/WritableTransaction.js~WritableTransaction#aborted",
    "member"
  ],
  [
    "js/writabletransaction.js~writabletransaction#canceled",
    "class/js/WritableTransaction.js~WritableTransaction.html#instance-member-canceled",
    "js/WritableTransaction.js~WritableTransaction#canceled",
    "member"
  ],
  [
    "js/writabletransaction.js~writabletransaction#constructor",
    "class/js/WritableTransaction.js~WritableTransaction.html#instance-constructor-constructor",
    "js/WritableTransaction.js~WritableTransaction#constructor",
    "method"
  ],
  [
    "js/writabletransaction.js~writabletransaction#pause",
    "class/js/WritableTransaction.js~WritableTransaction.html#instance-method-pause",
    "js/WritableTransaction.js~WritableTransaction#pause",
    "method"
  ],
  [
    "js/writabletransaction.js~writabletransaction#readablebufferfull",
    "class/js/WritableTransaction.js~WritableTransaction.html#instance-member-readableBufferFull",
    "js/WritableTransaction.js~WritableTransaction#readableBufferFull",
    "member"
  ],
  [
    "js/writabletransaction.js~writabletransaction#resume",
    "class/js/WritableTransaction.js~WritableTransaction.html#instance-method-resume",
    "js/WritableTransaction.js~WritableTransaction#resume",
    "method"
  ],
  [
    "js/writabletransaction.js~writabletransaction#stop",
    "class/js/WritableTransaction.js~WritableTransaction.html#instance-method-stop",
    "js/WritableTransaction.js~WritableTransaction#stop",
    "method"
  ],
  [
    "js/writabletransaction.js~writabletransaction#stream",
    "class/js/WritableTransaction.js~WritableTransaction.html#instance-member-stream",
    "js/WritableTransaction.js~WritableTransaction#stream",
    "member"
  ],
  [
    "js/index.js",
    "file/js/index.js.html",
    "js/index.js",
    "file"
  ],
  [
    "js/signaler/base.js",
    "file/js/signaler/Base.js.html",
    "js/signaler/Base.js",
    "file"
  ],
  [
    "js/signaler/base.js~signalerbase#close",
    "class/js/signaler/Base.js~SignalerBase.html#instance-method-close",
    "js/signaler/Base.js~SignalerBase#close",
    "method"
  ],
  [
    "js/signaler/base.js~signalerbase#connected",
    "class/js/signaler/Base.js~SignalerBase.html#instance-method-connected",
    "js/signaler/Base.js~SignalerBase#connected",
    "method"
  ],
  [
    "js/signaler/base.js~signalerbase#constructor",
    "class/js/signaler/Base.js~SignalerBase.html#instance-constructor-constructor",
    "js/signaler/Base.js~SignalerBase#constructor",
    "method"
  ],
  [
    "js/signaler/base.js~signalerbase#disconnected",
    "class/js/signaler/Base.js~SignalerBase.html#instance-method-disconnected",
    "js/signaler/Base.js~SignalerBase#disconnected",
    "method"
  ],
  [
    "js/signaler/base.js~signalerbase#failed",
    "class/js/signaler/Base.js~SignalerBase.html#instance-method-failed",
    "js/signaler/Base.js~SignalerBase#failed",
    "method"
  ],
  [
    "js/signaler/base.js~signalerbase#on",
    "class/js/signaler/Base.js~SignalerBase.html#instance-method-on",
    "js/signaler/Base.js~SignalerBase#on",
    "method"
  ],
  [
    "js/signaler/base.js~signalerbase#options",
    "class/js/signaler/Base.js~SignalerBase.html#instance-member-options",
    "js/signaler/Base.js~SignalerBase#options",
    "member"
  ],
  [
    "js/signaler/base.js~signalerbase#ready",
    "class/js/signaler/Base.js~SignalerBase.html#instance-member-ready",
    "js/signaler/Base.js~SignalerBase#ready",
    "member"
  ],
  [
    "js/signaler/base.js~signalerbase#receive",
    "class/js/signaler/Base.js~SignalerBase.html#instance-method-receive",
    "js/signaler/Base.js~SignalerBase#receive",
    "method"
  ],
  [
    "js/signaler/base.js~signalerbase#send",
    "class/js/signaler/Base.js~SignalerBase.html#instance-method-send",
    "js/signaler/Base.js~SignalerBase#send",
    "method"
  ],
  [
    "js/signaler/base.js~signalerbase#start",
    "class/js/signaler/Base.js~SignalerBase.html#instance-method-start",
    "js/signaler/Base.js~SignalerBase#start",
    "method"
  ],
  [
    "js/signaler/base.js~signalerbase#unhandledmsg",
    "class/js/signaler/Base.js~SignalerBase.html#instance-member-unhandledMsg",
    "js/signaler/Base.js~SignalerBase#unhandledMsg",
    "member"
  ],
  [
    "js/signaler/localsignaler.js",
    "file/js/signaler/LocalSignaler.js.html",
    "js/signaler/LocalSignaler.js",
    "file"
  ],
  [
    "js/signaler/localsignaler.js~localsignaler#bc",
    "class/js/signaler/LocalSignaler.js~LocalSignaler.html#instance-member-bc",
    "js/signaler/LocalSignaler.js~LocalSignaler#bc",
    "member"
  ],
  [
    "js/signaler/localsignaler.js~localsignaler#close",
    "class/js/signaler/LocalSignaler.js~LocalSignaler.html#instance-method-close",
    "js/signaler/LocalSignaler.js~LocalSignaler#close",
    "method"
  ],
  [
    "js/signaler/localsignaler.js~localsignaler#config",
    "class/js/signaler/LocalSignaler.js~LocalSignaler.html#instance-member-config",
    "js/signaler/LocalSignaler.js~LocalSignaler#config",
    "member"
  ],
  [
    "js/signaler/localsignaler.js~localsignaler#constructor",
    "class/js/signaler/LocalSignaler.js~LocalSignaler.html#instance-constructor-constructor",
    "js/signaler/LocalSignaler.js~LocalSignaler#constructor",
    "method"
  ],
  [
    "js/signaler/localsignaler.js~localsignaler#heartbeattimeouttimer",
    "class/js/signaler/LocalSignaler.js~LocalSignaler.html#instance-member-heartbeatTimeoutTimer",
    "js/signaler/LocalSignaler.js~LocalSignaler#heartbeatTimeoutTimer",
    "member"
  ],
  [
    "js/signaler/localsignaler.js~localsignaler#id",
    "class/js/signaler/LocalSignaler.js~LocalSignaler.html#instance-member-id",
    "js/signaler/LocalSignaler.js~LocalSignaler#id",
    "member"
  ],
  [
    "js/signaler/localsignaler.js~localsignaler#receiveheartbeat",
    "class/js/signaler/LocalSignaler.js~LocalSignaler.html#instance-method-receiveHeartbeat",
    "js/signaler/LocalSignaler.js~LocalSignaler#receiveHeartbeat",
    "method"
  ],
  [
    "js/signaler/localsignaler.js~localsignaler#send",
    "class/js/signaler/LocalSignaler.js~LocalSignaler.html#instance-method-send",
    "js/signaler/LocalSignaler.js~LocalSignaler#send",
    "method"
  ],
  [
    "js/signaler/localsignaler.js~localsignaler#sendheartbeattimer",
    "class/js/signaler/LocalSignaler.js~LocalSignaler.html#instance-member-sendHeartbeatTimer",
    "js/signaler/LocalSignaler.js~LocalSignaler#sendHeartbeatTimer",
    "member"
  ],
  [
    "js/signaler/localsignaler.js~localsignaler#sender",
    "class/js/signaler/LocalSignaler.js~LocalSignaler.html#instance-member-sender",
    "js/signaler/LocalSignaler.js~LocalSignaler#sender",
    "member"
  ],
  [
    "js/signaler/index.js",
    "file/js/signaler/index.js.html",
    "js/signaler/index.js",
    "file"
  ],
  [
    "js/util/intervaltimer.js",
    "file/js/util/IntervalTimer.js.html",
    "js/util/IntervalTimer.js",
    "file"
  ],
  [
    "js/util/intervaltimer.js~intervaltimer#callback",
    "class/js/util/IntervalTimer.js~IntervalTimer.html#instance-member-callback",
    "js/util/IntervalTimer.js~IntervalTimer#callback",
    "member"
  ],
  [
    "js/util/intervaltimer.js~intervaltimer#clear",
    "class/js/util/IntervalTimer.js~IntervalTimer.html#instance-method-clear",
    "js/util/IntervalTimer.js~IntervalTimer#clear",
    "method"
  ],
  [
    "js/util/intervaltimer.js~intervaltimer#constructor",
    "class/js/util/IntervalTimer.js~IntervalTimer.html#instance-constructor-constructor",
    "js/util/IntervalTimer.js~IntervalTimer#constructor",
    "method"
  ],
  [
    "js/util/intervaltimer.js~intervaltimer#interval",
    "class/js/util/IntervalTimer.js~IntervalTimer.html#instance-member-interval",
    "js/util/IntervalTimer.js~IntervalTimer#interval",
    "member"
  ],
  [
    "js/util/intervaltimer.js~intervaltimer#intervalid",
    "class/js/util/IntervalTimer.js~IntervalTimer.html#instance-member-intervalID",
    "js/util/IntervalTimer.js~IntervalTimer#intervalID",
    "member"
  ],
  [
    "js/util/intervaltimer.js~intervaltimer#options",
    "class/js/util/IntervalTimer.js~IntervalTimer.html#instance-member-options",
    "js/util/IntervalTimer.js~IntervalTimer#options",
    "member"
  ],
  [
    "js/util/intervaltimer.js~intervaltimer#reset",
    "class/js/util/IntervalTimer.js~IntervalTimer.html#instance-method-reset",
    "js/util/IntervalTimer.js~IntervalTimer#reset",
    "method"
  ],
  [
    "js/util/intervaltimer.js~intervaltimer#set",
    "class/js/util/IntervalTimer.js~IntervalTimer.html#instance-method-set",
    "js/util/IntervalTimer.js~IntervalTimer#set",
    "method"
  ],
  [
    "js/util/listenermanager.js",
    "file/js/util/ListenerManager.js.html",
    "js/util/ListenerManager.js",
    "file"
  ],
  [
    "js/util/listenermanager.js~eventlistenerentry",
    "typedef/index.html#static-typedef-EventListenerEntry",
    "js/util/ListenerManager.js~EventListenerEntry",
    "typedef"
  ],
  [
    "js/util/listenermanager.js~listenermanager#add",
    "class/js/util/ListenerManager.js~ListenerManager.html#instance-method-add",
    "js/util/ListenerManager.js~ListenerManager#add",
    "method"
  ],
  [
    "js/util/listenermanager.js~listenermanager#clear",
    "class/js/util/ListenerManager.js~ListenerManager.html#instance-method-clear",
    "js/util/ListenerManager.js~ListenerManager#clear",
    "method"
  ],
  [
    "js/util/listenermanager.js~listenermanager#constructor",
    "class/js/util/ListenerManager.js~ListenerManager.html#instance-constructor-constructor",
    "js/util/ListenerManager.js~ListenerManager#constructor",
    "method"
  ],
  [
    "js/util/listenermanager.js~listenermanager#listeners",
    "class/js/util/ListenerManager.js~ListenerManager.html#instance-member-listeners",
    "js/util/ListenerManager.js~ListenerManager#listeners",
    "member"
  ],
  [
    "js/util/mitt.js",
    "file/js/util/Mitt.js.html",
    "js/util/Mitt.js",
    "file"
  ],
  [
    "js/util/mitt.js~eventhandler",
    "typedef/index.html#static-typedef-EventHandler",
    "js/util/Mitt.js~EventHandler",
    "typedef"
  ],
  [
    "js/util/mitt.js~mitt#addeventlistener",
    "class/js/util/Mitt.js~Mitt.html#instance-method-addEventListener",
    "js/util/Mitt.js~Mitt#addEventListener",
    "method"
  ],
  [
    "js/util/mitt.js~mitt#all",
    "class/js/util/Mitt.js~Mitt.html#instance-member-all",
    "js/util/Mitt.js~Mitt#all",
    "member"
  ],
  [
    "js/util/mitt.js~mitt#constructor",
    "class/js/util/Mitt.js~Mitt.html#instance-constructor-constructor",
    "js/util/Mitt.js~Mitt#constructor",
    "method"
  ],
  [
    "js/util/mitt.js~mitt#emit",
    "class/js/util/Mitt.js~Mitt.html#instance-method-emit",
    "js/util/Mitt.js~Mitt#emit",
    "method"
  ],
  [
    "js/util/mitt.js~mitt#off",
    "class/js/util/Mitt.js~Mitt.html#instance-method-off",
    "js/util/Mitt.js~Mitt#off",
    "method"
  ],
  [
    "js/util/mitt.js~mitt#on",
    "class/js/util/Mitt.js~Mitt.html#instance-method-on",
    "js/util/Mitt.js~Mitt#on",
    "method"
  ],
  [
    "js/util/mitt.js~mitt#once",
    "class/js/util/Mitt.js~Mitt.html#instance-method-once",
    "js/util/Mitt.js~Mitt#once",
    "method"
  ],
  [
    "js/util/mitt.js~mitt#removeeventlistener",
    "class/js/util/Mitt.js~Mitt.html#instance-method-removeEventListener",
    "js/util/Mitt.js~Mitt#removeEventListener",
    "method"
  ],
  [
    "js/util/observableentry.js",
    "file/js/util/ObservableEntry.js.html",
    "js/util/ObservableEntry.js",
    "file"
  ],
  [
    "js/util/observableentry.js~observableentry#callbacks",
    "class/js/util/ObservableEntry.js~ObservableEntry.html#instance-member-callbacks",
    "js/util/ObservableEntry.js~ObservableEntry#callbacks",
    "member"
  ],
  [
    "js/util/observableentry.js~observableentry#conditions",
    "class/js/util/ObservableEntry.js~ObservableEntry.html#instance-member-conditions",
    "js/util/ObservableEntry.js~ObservableEntry#conditions",
    "member"
  ],
  [
    "js/util/observableentry.js~observableentry#constructor",
    "class/js/util/ObservableEntry.js~ObservableEntry.html#instance-constructor-constructor",
    "js/util/ObservableEntry.js~ObservableEntry#constructor",
    "method"
  ],
  [
    "js/util/observableentry.js~observableentry#get",
    "class/js/util/ObservableEntry.js~ObservableEntry.html#instance-method-get",
    "js/util/ObservableEntry.js~ObservableEntry#get",
    "method"
  ],
  [
    "js/util/observableentry.js~observableentry#registercallback",
    "class/js/util/ObservableEntry.js~ObservableEntry.html#instance-method-registerCallback",
    "js/util/ObservableEntry.js~ObservableEntry#registerCallback",
    "method"
  ],
  [
    "js/util/observableentry.js~observableentry#set",
    "class/js/util/ObservableEntry.js~ObservableEntry.html#instance-method-set",
    "js/util/ObservableEntry.js~ObservableEntry#set",
    "method"
  ],
  [
    "js/util/observableentry.js~observableentry#testcondition",
    "class/js/util/ObservableEntry.js~ObservableEntry.html#instance-method-testCondition",
    "js/util/ObservableEntry.js~ObservableEntry#testCondition",
    "method"
  ],
  [
    "js/util/observableentry.js~observableentry#testconditionsall",
    "class/js/util/ObservableEntry.js~ObservableEntry.html#instance-method-testConditionsAll",
    "js/util/ObservableEntry.js~ObservableEntry#testConditionsAll",
    "method"
  ],
  [
    "js/util/observableentry.js~observableentry#val",
    "class/js/util/ObservableEntry.js~ObservableEntry.html#instance-member-val",
    "js/util/ObservableEntry.js~ObservableEntry#val",
    "member"
  ],
  [
    "js/util/observableentry.js~waitentry#cancel",
    "class/js/util/ObservableEntry.js~WaitEntry.html#instance-member-cancel",
    "js/util/ObservableEntry.js~WaitEntry#cancel",
    "member"
  ],
  [
    "js/util/observableentry.js~waitentry#constructor",
    "class/js/util/ObservableEntry.js~WaitEntry.html#instance-constructor-constructor",
    "js/util/ObservableEntry.js~WaitEntry#constructor",
    "method"
  ],
  [
    "js/util/observableentry.js~waitentry#observableentry",
    "class/js/util/ObservableEntry.js~WaitEntry.html#instance-member-observableEntry",
    "js/util/ObservableEntry.js~WaitEntry#observableEntry",
    "member"
  ],
  [
    "js/util/observableentry.js~waitentry#onchange",
    "class/js/util/ObservableEntry.js~WaitEntry.html#instance-method-onChange",
    "js/util/ObservableEntry.js~WaitEntry#onChange",
    "method"
  ],
  [
    "js/util/observableentry.js~waitentry#once",
    "class/js/util/ObservableEntry.js~WaitEntry.html#instance-member-once",
    "js/util/ObservableEntry.js~WaitEntry#once",
    "member"
  ],
  [
    "js/util/observableentry.js~waitentry#promisecallbacks",
    "class/js/util/ObservableEntry.js~WaitEntry.html#instance-member-promiseCallbacks",
    "js/util/ObservableEntry.js~WaitEntry#promiseCallbacks",
    "member"
  ],
  [
    "js/util/observableentry.js~waitentry#resolve",
    "class/js/util/ObservableEntry.js~WaitEntry.html#instance-method-resolve",
    "js/util/ObservableEntry.js~WaitEntry#resolve",
    "method"
  ],
  [
    "js/util/observableentry.js~waitentry#resolved",
    "class/js/util/ObservableEntry.js~WaitEntry.html#instance-member-resolved",
    "js/util/ObservableEntry.js~WaitEntry#resolved",
    "member"
  ],
  [
    "js/util/observableentry.js~waitentry#then",
    "class/js/util/ObservableEntry.js~WaitEntry.html#instance-method-then",
    "js/util/ObservableEntry.js~WaitEntry#then",
    "method"
  ],
  [
    "js/util/observableentry.js~waitentry#tobe",
    "class/js/util/ObservableEntry.js~WaitEntry.html#instance-method-toBe",
    "js/util/ObservableEntry.js~WaitEntry#toBe",
    "method"
  ],
  [
    "js/util/observableentry.js~waitentry#tobechanged",
    "class/js/util/ObservableEntry.js~WaitEntry.html#instance-method-toBeChanged",
    "js/util/ObservableEntry.js~WaitEntry#toBeChanged",
    "method"
  ],
  [
    "js/util/observableentry.js~waitentry#tobedefined",
    "class/js/util/ObservableEntry.js~WaitEntry.html#instance-method-toBeDefined",
    "js/util/ObservableEntry.js~WaitEntry#toBeDefined",
    "method"
  ],
  [
    "js/util/observableentry.js~waitentry#tofulfill",
    "class/js/util/ObservableEntry.js~WaitEntry.html#instance-method-toFulfill",
    "js/util/ObservableEntry.js~WaitEntry#toFulfill",
    "method"
  ],
  [
    "js/util/observableentry.js~waitentry#unmatchedcallback",
    "class/js/util/ObservableEntry.js~WaitEntry.html#instance-member-unmatchedCallback",
    "js/util/ObservableEntry.js~WaitEntry#unmatchedCallback",
    "member"
  ],
  [
    "js/util/observablemap.js",
    "file/js/util/ObservableMap.js.html",
    "js/util/ObservableMap.js",
    "file"
  ],
  [
    "js/util/observablemap.js~observablemap#clear",
    "class/js/util/ObservableMap.js~ObservableMap.html#instance-method-clear",
    "js/util/ObservableMap.js~ObservableMap#clear",
    "method"
  ],
  [
    "js/util/observablemap.js~observablemap#constructor",
    "class/js/util/ObservableMap.js~ObservableMap.html#instance-constructor-constructor",
    "js/util/ObservableMap.js~ObservableMap#constructor",
    "method"
  ],
  [
    "js/util/observablemap.js~observablemap#delete",
    "class/js/util/ObservableMap.js~ObservableMap.html#instance-method-delete",
    "js/util/ObservableMap.js~ObservableMap#delete",
    "method"
  ],
  [
    "js/util/observablemap.js~observablemap#get",
    "class/js/util/ObservableMap.js~ObservableMap.html#instance-method-get",
    "js/util/ObservableMap.js~ObservableMap#get",
    "method"
  ],
  [
    "js/util/observablemap.js~observablemap#has",
    "class/js/util/ObservableMap.js~ObservableMap.html#instance-method-has",
    "js/util/ObservableMap.js~ObservableMap#has",
    "method"
  ],
  [
    "js/util/observablemap.js~observablemap#observableentries",
    "class/js/util/ObservableMap.js~ObservableMap.html#instance-member-observableEntries",
    "js/util/ObservableMap.js~ObservableMap#observableEntries",
    "member"
  ],
  [
    "js/util/observablemap.js~observablemap#set",
    "class/js/util/ObservableMap.js~ObservableMap.html#instance-method-set",
    "js/util/ObservableMap.js~ObservableMap#set",
    "method"
  ],
  [
    "js/util/observablemap.js~observablemap#wait",
    "class/js/util/ObservableMap.js~ObservableMap.html#instance-method-wait",
    "js/util/ObservableMap.js~ObservableMap#wait",
    "method"
  ],
  [
    "js/util/observablequeue.js",
    "file/js/util/ObservableQueue.js.html",
    "js/util/ObservableQueue.js",
    "file"
  ],
  [
    "js/util/observablequeue.js~observablequeue#pushes",
    "class/js/util/ObservableQueue.js~ObservableQueue.html#instance-method-pushes",
    "js/util/ObservableQueue.js~ObservableQueue#pushes",
    "method"
  ],
  [
    "js/util/queue.js",
    "file/js/util/Queue.js.html",
    "js/util/Queue.js",
    "file"
  ],
  [
    "js/util/queue.js~queue#[symbol.iterator]",
    "class/js/util/Queue.js~Queue.html#instance-method-[Symbol.iterator]",
    "js/util/Queue.js~Queue#[Symbol.iterator]",
    "method"
  ],
  [
    "js/util/queue.js~queue#constructor",
    "class/js/util/Queue.js~Queue.html#instance-constructor-constructor",
    "js/util/Queue.js~Queue#constructor",
    "method"
  ],
  [
    "js/util/queue.js~queue#data",
    "class/js/util/Queue.js~Queue.html#instance-member-data",
    "js/util/Queue.js~Queue#data",
    "member"
  ],
  [
    "js/util/queue.js~queue#flush",
    "class/js/util/Queue.js~Queue.html#instance-method-flush",
    "js/util/Queue.js~Queue#flush",
    "method"
  ],
  [
    "js/util/queue.js~queue#head",
    "class/js/util/Queue.js~Queue.html#instance-member-head",
    "js/util/Queue.js~Queue#head",
    "member"
  ],
  [
    "js/util/queue.js~queue#pop",
    "class/js/util/Queue.js~Queue.html#instance-method-pop",
    "js/util/Queue.js~Queue#pop",
    "method"
  ],
  [
    "js/util/queue.js~queue#push",
    "class/js/util/Queue.js~Queue.html#instance-method-push",
    "js/util/Queue.js~Queue#push",
    "method"
  ],
  [
    "js/util/queue.js~queue#size",
    "class/js/util/Queue.js~Queue.html#instance-get-size",
    "js/util/Queue.js~Queue#size",
    "member"
  ],
  [
    "js/util/queue.js~queue#tail",
    "class/js/util/Queue.js~Queue.html#instance-member-tail",
    "js/util/Queue.js~Queue#tail",
    "member"
  ],
  [
    "js/util/timeouttimer.js",
    "file/js/util/TimeoutTimer.js.html",
    "js/util/TimeoutTimer.js",
    "file"
  ],
  [
    "js/util/timeouttimer.js~timeouttimer#callback",
    "class/js/util/TimeoutTimer.js~TimeoutTimer.html#instance-member-callback",
    "js/util/TimeoutTimer.js~TimeoutTimer#callback",
    "member"
  ],
  [
    "js/util/timeouttimer.js~timeouttimer#clear",
    "class/js/util/TimeoutTimer.js~TimeoutTimer.html#instance-method-clear",
    "js/util/TimeoutTimer.js~TimeoutTimer#clear",
    "method"
  ],
  [
    "js/util/timeouttimer.js~timeouttimer#constructor",
    "class/js/util/TimeoutTimer.js~TimeoutTimer.html#instance-constructor-constructor",
    "js/util/TimeoutTimer.js~TimeoutTimer#constructor",
    "method"
  ],
  [
    "js/util/timeouttimer.js~timeouttimer#options",
    "class/js/util/TimeoutTimer.js~TimeoutTimer.html#instance-member-options",
    "js/util/TimeoutTimer.js~TimeoutTimer#options",
    "member"
  ],
  [
    "js/util/timeouttimer.js~timeouttimer#reset",
    "class/js/util/TimeoutTimer.js~TimeoutTimer.html#instance-method-reset",
    "js/util/TimeoutTimer.js~TimeoutTimer#reset",
    "method"
  ],
  [
    "js/util/timeouttimer.js~timeouttimer#set",
    "class/js/util/TimeoutTimer.js~TimeoutTimer.html#instance-method-set",
    "js/util/TimeoutTimer.js~TimeoutTimer#set",
    "method"
  ],
  [
    "js/util/timeouttimer.js~timeouttimer#timeout",
    "class/js/util/TimeoutTimer.js~TimeoutTimer.html#instance-member-timeout",
    "js/util/TimeoutTimer.js~TimeoutTimer#timeout",
    "member"
  ],
  [
    "js/util/timeouttimer.js~timeouttimer#timeoutid",
    "class/js/util/TimeoutTimer.js~TimeoutTimer.html#instance-member-timeoutID",
    "js/util/TimeoutTimer.js~TimeoutTimer#timeoutID",
    "member"
  ],
  [
    "js/util/createlogger.js",
    "file/js/util/createLogger.js.html",
    "js/util/createLogger.js",
    "file"
  ],
  [
    "js/util/eta.js",
    "file/js/util/eta.js.html",
    "js/util/eta.js",
    "file"
  ],
  [
    "js/util/index.js",
    "file/js/util/index.js.html",
    "js/util/index.js",
    "file"
  ],
  [
    "js/util/once.js",
    "file/js/util/once.js.html",
    "js/util/once.js",
    "file"
  ],
  [
    "js/util/prettybytes.js",
    "file/js/util/prettyBytes.js.html",
    "js/util/prettyBytes.js",
    "file"
  ]
]